### ISSUE TITLE
Decode method does not support a struct type whose only members are also structs

### ISSUE THREAD

**Issue by JGMarshall** [joeshaw/envdecode#11]
Thanks for the library - I found it while reading Mat Ryer's book and immediately started using it in some small projects I'm writing while learning golang. During development I found the following.

Consider the following simple struct:

    type BrokenConfig struct {
        Jenkins struct {
            User string `env:"JENKINS_USER,required"`
            ApiToken string `env:"JENKINS_API_TOKEN,required"`
            URL string `env:"JENKINS_URL,required"`
        }
    }

envdecode.Decode on a struct of this type fails with ErrInvalidTarget even when all fields are supplied. Note that the only tagged fields are present within a sub-structure.

Trying envdecode.Decode with a small change (adding a single top-level tagged field) causes things to work:

    type WorkingConfig struct {
        Blah string `env:"DONT_CARE,default=foo"`
        Jenkins struct {
            User string `env:"JENKINS_USER,required"`
            ApiToken string `env:"JENKINS_API_TOKEN,required"`
            URL string `env:"JENKINS_URL,required"`
        }
    }

It would be nice if this bogus field (Blah) wasn't necessary.

**Comment by joeshaw** [comment]
Thanks, this is definitely a bug.  I'm looking into it now.

**Comment by JGMarshall** [comment]
Thanks for the fix.
