### ISSUE TITLE
missing " causes silent failure

### ISSUE THREAD

**Issue by jameshfisher** [joeshaw/envdecode#16]
We just had an issue where we forgot a final `"` in a struct tag. This led to the struct field being populated with the empty string (`""`). This was a silent failure, where it would be much nicer for the failure to have been loud and immediate at an earlier stage (compile time or early runtime).

The root cause AFAIK is the very weak guarantee given by https://golang.org/pkg/reflect/#StructTag.Get

Is there anything envdecode can do to improve this experience for developers?

**Comment by joeshaw** [comment]
ugh, that's so frustrating!  I've run into that with json tags in the past.  I'm not sure there's anything envdecode can do about it, but I'll take a look.

**Comment by jameshfisher** [comment]
@joeshaw thanks! I'm not sure envdecode can help either, but just thought we'd make you aware of the frustration :)

**Comment by joeshaw** [comment]
@jameshfisher do you use `go vet` or `golint` on your code base?  I think one of those would catch these types of errors, but I don't remember which one.

**Comment by jameshfisher** [comment]
@joeshaw ah yes, `go vet` catches it! Thanks very much, I think that's sufficient for us!
