### ISSUE TITLE
Return errors from duration and URL parsing that occur in Decode

### ISSUE THREAD

**Issue by jkakar** [joeshaw/envdecode#9]
In #8 @joeshaw said:

> As you commented, we might want to start returning errors if there
> is a problem parsing. Originally when it was just the primitive
> types it didn't seem like a big deal, but as we increasingly add
> more complex types like duration and URLs, we might want to start
> returning errors.
> 
> To maintain compatibility we might not want to return the error from
> the Decode function but instead add a function call after decoding
> to see if there are any errors. I'm not sure, but it's not blocking
> merging of this PR.

**Comment by jkakar** [comment]
I was thinking about returning parse errors wrapped in a new
`ErrParseError` error type from `Decode` and `MustDecode`.  I don't
see that as breaking backwards compatibility and it feels natural
because those calls should fail if parsing fails.  Requiring users to
call a `ErrorOccurred` function seems like a strange API to me.

**Comment by danp** [comment]
Can probably be closed, fixed by #19.
